---
- name: Wait until amq-streams application is correctly deployed
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_globex_ai_poc_amq_streams_application_name }}"
    namespace: "{{ ocp4_workload_globex_ai_poc_amq_streams_application_namespace }}"
  register: r_amqstreams_application
  retries: 40
  delay: 30
  until:
    - r_amqstreams_application.resources[0].status is defined
    - r_amqstreams_application.resources[0].status.health is defined
    - r_amqstreams_application.resources[0].status.health.status is defined
    - r_amqstreams_application.resources[0].status.health.status | length > 0
    - r_amqstreams_application.resources[0].status.health.status == "Healthy"
    - r_amqstreams_application.resources[0].status.sync is defined
    - r_amqstreams_application.resources[0].status.sync.status is defined
    - r_amqstreams_application.resources[0].status.sync.status | length > 0
    - r_amqstreams_application.resources[0].status.sync.status == "Synced"

- name: Deploy Globex application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-ai/globex-ai-application.yaml.j2') }}"
